- hosts: all     
  tasks:  
    - name: "Roda: sudo apt update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia
    
    - name: "Instala pacotes em lote"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - nginx
        - unzip

    - name: "Fazendo downlaod do tema"
      get_url:
        url: "https://github.com/startbootstrap/startbootstrap-sb-admin-2/archive/gh-pages.zip"
        dest: "/tmp/tema.zip"
    
    #- name: "Fazendo descompactação dos arquivos do WP"
      #unarchive:
        #src: "/tmp/wordpress.tar.gz"
        #dest: "/var/www"
        #remote_src: yes
      #become: yes
      
    #- name: "Configura o wp-config com as senhas"
      #replace:
        #path: '/var/www/wordpress/wp-config.php'
        #regexp: "{{ item.regex }}"
        #replace: "{{ item.value }}"
      #with_items:
        #- { regex: 'nome_do_banco_de_dados_aqui', value: 'banco_wordpress' }
        #- { regex: 'nome_de_usuario_aqui', value: 'root' }
        #- { regex: 'senha_aqui', value: 'root' }
      #become: yes
      
    #- name: "Trocando pasta do render do apache para o wordpress"
      #copy:
        #src: "apache/000-default.conf"
        #dest: "/etc/apache2/sites-available/000-default.conf"
      #become: yes
      #notify:
        #- "restart apache"
